# Generated by Django 5.2.4 on 2025-07-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_specialoffer_category_shop_catego_name_289c7e_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialoffer',
            options={'ordering': ['-start_date'], 'verbose_name': 'Специальное предложение', 'verbose_name_plural': 'Специальные предложения'},
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название акции')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(verbose_name='Описание акции')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания')),
                ('discount_percent', models.PositiveIntegerField(verbose_name='Процент скидки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('image', models.ImageField(blank=True, null=True, upload_to='promotions/')),
                ('products', models.ManyToManyField(related_name='promotions', to='shop.product')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['-start_date'], name='shop_promot_start_d_c8015c_idx'), models.Index(fields=['is_active'], name='shop_promot_is_acti_d06a33_idx')],
            },
        ),
    ]
